### ISSUE TITLE
Undefined not callable

### ISSUE THREAD

**Issue by davidmtobias** [TrestleAdmin/trestle#172]
Hi guys,

After installing Trestle in a new Rails app following the four steps of "Getting Started seccion" I get an error on line 17 from layouts/trestle/admin.html.erb:

Showing F:/RoR-environments/rails531/lib/ruby/gems/2.5.0/gems/trestle-0.8.11/app/views/layouts/trestle/admin.html.erb where line #17 raised:

undefined not callable

(execjs):1
execjs (2.7.0) lib/execjs/duktape_runtime.rb:9:in `exec_string'
execjs (2.7.0) lib/execjs/duktape_runtime.rb:9:in `initialize'
execjs (2.7.0) lib/execjs/runtime.rb:57:in `new'
execjs (2.7.0) lib/execjs/runtime.rb:57:in `compile'
execjs (2.7.0) lib/execjs/module.rb:27:in `compile'
autoprefixer-rails (9.4.3) lib/autoprefixer-rails/processor.rb:167:in `runtime'
autoprefixer-rails (9.4.3) lib/autoprefixer-rails/processor.rb:37:in `process'
autoprefixer-rails (9.4.3) lib/autoprefixer-rails/sprockets.rb:20:in `run'
autoprefixer-rails (9.4.3) lib/autoprefixer-rails/sprockets.rb:14:in `call' 
[...]

ActionView::Template::Error (undefined not callable):
    14:
    15:     <title><%= [yield(:title), Trestle.config.site_title].join(' :: ') %></title>
    16:
    **17:     <%= stylesheet_link_tag "trestle/admin", 'data-turbolinks-track': 'reload' %>**
    18:
    19:     <%= hook :stylesheets %>
    20:
 
My development environment is:
ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]
Rails 5.2.2
Windows 10

I appreciate your help
Thanks
David

**Comment by davidmtobias** [comment]
Hi again,
I've solved my the issue adding the following line into **_config/boot.rb_**

`ENV['EXECJS_RUNTIME'] = 'Node'`

Have a nice new year!
