### ISSUE TITLE
Remove sass-rails/sassc-rails requirement with Rails 6

### ISSUE THREAD

**Issue by spohlenz** [TrestleAdmin/trestle#242]
From https://github.com/TrestleAdmin/trestle/pull/195#issuecomment-533197892:

> Also, it'd be worth mentioning somewhere in the README that either `sass-rails` or `sassc-rails` needs to be included in your Gemfile or `rails generate trestle:install` will fail.
> 
> ```
> $ rails generate trestle:install
> ...
> trestle/lib/trestle/engine.rb:7:in `<class:Engine>'
> railties-6.0.0/lib/rails/railtie/configuration.rb:97:in `method_missing': undefined method `assets' for #<Rails::Engine::Configuration:0x00007febd7362638> (NoMethodError)
> ```

**Comment by spohlenz** [comment]
Fixed in a52ff1a. Automatically require the Sprockets railtie if not already loaded. No errors occur if sass-rails/sassc-rails aren't loaded but theme compilation won't be enabled.
