### ISSUE TITLE
isWithActiveTrigger null object

### ISSUE THREAD

**Issue by bendangelo** [TrestleAdmin/trestle#516]
```
admin-3bbfa744.js:42 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at li._isWithActiveTrigger (admin-3bbfa744.js:42:49198)
    at e (admin-3bbfa744.js:42:45313)
    at x (admin-3bbfa744.js:42:2624)
    at HTMLDivElement.s (admin-3bbfa744.js:42:2763)
    at d (admin-3bbfa744.js:42:1234)
    at admin-3bbfa744.js:42:2814
```

The code linked go here:
```
 _isWithActiveTrigger() {
                        return Object.values(this._activeTrigger).includes(!0)
                    }
```

This happens on the form page for a model. It doesn't happen every time. I hope this is enough to fix it.

**Comment by spohlenz** [comment]
I'm aware of this happening occasionally although as far as I am aware, the worst of its effects is the error messages in the console logs.

I so far haven't been able to find a working workaround, so I do think we'll have to wait for it to be fixed upstream in Bootstrap. Please leave this issue open until then though.

* https://github.com/twbs/bootstrap/issues/37474
* https://github.com/twbs/bootstrap/pull/40856
