### ISSUE TITLE
Mongoid-Trestle

### ISSUE THREAD

**Issue by kenzo2013** [TrestleAdmin/trestle#75]
I steel working with mongo but CRUD don't work. When i try to create an brand on my db i have error like this 

`NoMethodError in BrandsAdmin::AdminController#create undefined method `_id' for "":String Extracted source (around line #62): #60 # @since 2.1.0 #61 def <<(document) *62 _added[document._id] = document #63 self #64 end #65 alias :push :<< Extracted source (around line #227): #225 def append(document) #226 execute_callback :before_add, document *227 target.push(document) #228 characterize_one(document) #229 bind_one(document) #230 execute_callback :after_add, document Extracted source (around line #49): #47 return concat(docs) if docs.size > 1 #48 if doc = docs.first *49 append(doc) #50 base.add_to_set(foreign_key => doc.send(__metadata.primary_key)) #51 if child_persistable?(doc) #52 doc.save Rails.root: /Users/simon/work/rails_projects/radar/wire Framework Trace mongoid (6.2.1) lib/mongoid/relations/targets/enumerable.rb:62:in `<<' mongoid (6.2.1) lib/mongoid/relations/referenced/many_to_many.rb:227:in `append' mongoid (6.2.1) lib/mongoid/relations/referenced/many_to_many.rb:49:in `<<' mongoid (6.2.1) lib/mongoid/relations/referenced/many_to_many.rb:194:in `substitute' mongoid (6.2.1) lib/mongoid/relations/accessors.rb:231:in `block (2 levels) in setter' mongoid (6.2.1) lib/mongoid/relations/accessors.rb:139:in `without_autobuild' mongoid (6.2.1) lib/mongoid/relations/accessors.rb:228:in `block in setter' mongoid (6.2.1) lib/mongoid/attributes/processing.rb:140:in `block in process_relations' mongoid (6.2.1) lib/mongoid/attributes/processing.rb:135:in `each_pair' mongoid (6.2.1) lib/mongoid/attributes/processing.rb:135:in `process_relations' mongoid (6.2.1) lib/mongoid/attributes/processing.rb:123:in `process_pending' mongoid (6.2.1) lib/mongoid/attributes/processing.rb:29:in `process_attributes' mongoid (6.2.1) lib/mongoid/document.rb:119:in `block in initialize' mongoid (6.2.1) lib/mongoid/threaded/lifecycle.rb:89:in `_building' mongoid (6.2.1) lib/mongoid/document.rb:114:in `initialize' trestle (0.8.6) lib/trestle/adapters/active_record_adapter.rb:13:in `new' trestle (0.8.6) lib/trestle/adapters/active_record_adapter.rb:13:in `build_instance' trestle (0.8.6) lib/trestle/resource.rb:29:in `public_send' trestle (0.8.6) lib/trestle/resource.rb:29:in `block in adapter_method' trestle (0.8.6) lib/trestle/resource/controller.rb:27:in `create' actionpack (5.1.4) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action' actionpack (5.1.4) lib/abstract_controller/base.rb:186:in `process_action' actionpack (5.1.4) lib/action_controller/metal/rendering.rb:30:in `process_action' actionpack (5.1.4) lib/abstract_controller/callbacks.rb:20:in `block in process_action' activesupport (5.1.4) lib/active_support/callbacks.rb:131:in `run_callbacks' actionpack (5.1.4) lib/abstract_controller/callbacks.rb:19:in `process_action' actionpack (5.1.4) lib/action_controller/metal/rescue.rb:20:in `process_action' actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action' activesupport (5.1.4) lib/active_support/notifications.rb:166:in `block in instrument' activesupport (5.1.4) lib/active_support/notifications/instrumenter.rb:21:in `instrument' activesupport (5.1.4) lib/active_support/notifications.rb:166:in `instrument' actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:30:in `process_action' actionpack (5.1.4) lib/action_controller/metal/params_wrapper.rb:252:in `process_action' actionpack (5.1.4) lib/abstract_controller/base.rb:124:in `process' actionview (5.1.4) lib/action_view/rendering.rb:30:in `process' actionpack (5.1.4) lib/action_controller/metal.rb:189:in `dispatch' actionpack (5.1.4) lib/action_controller/metal.rb:253:in `dispatch' actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:49:in `dispatch' actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:31:in `serve' actionpack (5.1.4) lib/action_dispatch/journey/router.rb:50:in `block in serve' actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `each' actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `serve' actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:834:in `call' railties (5.1.4) lib/rails/engine.rb:522:in `call' railties (5.1.4) lib/rails/railtie.rb:185:in `public_send' railties (5.1.4) lib/rails/railtie.rb:185:in `method_missing' actionpack (5.1.4) lib/action_dispatch/routing/mapper.rb:17:in `block in ' actionpack (5.1.4) lib/action_dispatch/routing/mapper.rb:46:in `serve' actionpack (5.1.4) lib/action_dispatch/journey/router.rb:50:in `block in serve' actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `each' actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `serve' actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:834:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' rack-pjax (1.0.0) lib/rack/pjax.rb:12:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' omniauth (1.7.1) lib/omniauth/strategy.rb:190:in `call!' omniauth (1.7.1) lib/omniauth/strategy.rb:168:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' scout_apm (2.1.32) lib/scout_apm/instant/middleware.rb:53:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' scout_apm (2.1.32) lib/scout_apm/middleware.rb:15:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' rack (2.0.3) lib/rack/deflater.rb:34:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' remotipart (1.3.1) lib/remotipart/middleware.rb:32:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' warden (1.2.7) lib/warden/manager.rb:36:in `block in call' warden (1.2.7) lib/warden/manager.rb:35:in `catch' warden (1.2.7) lib/warden/manager.rb:35:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' rack (2.0.3) lib/rack/etag.rb:25:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' rack (2.0.3) lib/rack/conditional_get.rb:38:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' rack (2.0.3) lib/rack/head.rb:12:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context' rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' actionpack (5.1.4) lib/action_dispatch/middleware/cookies.rb:613:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' actionpack (5.1.4) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call' activesupport (5.1.4) lib/active_support/callbacks.rb:97:in `run_callbacks' actionpack (5.1.4) lib/action_dispatch/middleware/callbacks.rb:24:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' airbrake (7.1.0) lib/airbrake/rack/middleware.rb:52:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' actionpack (5.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' actionpack (5.1.4) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' chewy (0.10.1) lib/chewy/railtie.rb:19:in `block in call' chewy (0.10.1) lib/chewy/strategy.rb:70:in `wrap' chewy (0.10.1) lib/chewy.rb:200:in `strategy' chewy (0.10.1) lib/chewy/railtie.rb:19:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' railties (5.1.4) lib/rails/rack/logger.rb:36:in `call_app' railties (5.1.4) lib/rails/rack/logger.rb:24:in `block in call' activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `block in tagged' activesupport (5.1.4) lib/active_support/tagged_logging.rb:26:in `tagged' activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `tagged' railties (5.1.4) lib/rails/rack/logger.rb:24:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' actionpack (5.1.4) lib/action_dispatch/middleware/remote_ip.rb:79:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' actionpack (5.1.4) lib/action_dispatch/middleware/request_id.rb:25:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' rack (2.0.3) lib/rack/method_override.rb:22:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' rack (2.0.3) lib/rack/runtime.rb:22:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' activesupport (5.1.4) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' actionpack (5.1.4) lib/action_dispatch/middleware/static.rb:125:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' rack (2.0.3) lib/rack/sendfile.rb:111:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' hirefire-resource (0.4.2) lib/hirefire/middleware.rb:41:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' railties (5.1.4) lib/rails/engine.rb:522:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' puma (3.10.0) lib/puma/configuration.rb:225:in `call' puma (3.10.0) lib/puma/server.rb:605:in `handle_request' puma (3.10.0) lib/puma/server.rb:437:in `process_client' puma (3.10.0) lib/puma/server.rb:301:in `block in run' puma (3.10.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread' Full Trace mongoid (6.2.1) lib/mongoid/relations/targets/enumerable.rb:62:in `<<' mongoid (6.2.1) lib/mongoid/relations/referenced/many_to_many.rb:227:in `append' mongoid (6.2.1) lib/mongoid/relations/referenced/many_to_many.rb:49:in `<<' mongoid (6.2.1) lib/mongoid/relations/referenced/many_to_many.rb:194:in `substitute' mongoid (6.2.1) lib/mongoid/relations/accessors.rb:231:in `block (2 levels) in setter' mongoid (6.2.1) lib/mongoid/relations/accessors.rb:139:in `without_autobuild' mongoid (6.2.1) lib/mongoid/relations/accessors.rb:228:in `block in setter' mongoid (6.2.1) lib/mongoid/attributes/processing.rb:140:in `block in process_relations' mongoid (6.2.1) lib/mongoid/attributes/processing.rb:135:in `each_pair' mongoid (6.2.1) lib/mongoid/attributes/processing.rb:135:in `process_relations' mongoid (6.2.1) lib/mongoid/attributes/processing.rb:123:in `process_pending' mongoid (6.2.1) lib/mongoid/attributes/processing.rb:29:in `process_attributes' mongoid (6.2.1) lib/mongoid/document.rb:119:in `block in initialize' mongoid (6.2.1) lib/mongoid/threaded/lifecycle.rb:89:in `_building' mongoid (6.2.1) lib/mongoid/document.rb:114:in `initialize' trestle (0.8.6) lib/trestle/adapters/active_record_adapter.rb:13:in `new' trestle (0.8.6) lib/trestle/adapters/active_record_adapter.rb:13:in `build_instance' trestle (0.8.6) lib/trestle/resource.rb:29:in `public_send' trestle (0.8.6) lib/trestle/resource.rb:29:in `block in adapter_method' trestle (0.8.6) lib/trestle/resource/controller.rb:27:in `create' actionpack (5.1.4) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action' actionpack (5.1.4) lib/abstract_controller/base.rb:186:in `process_action' actionpack (5.1.4) lib/action_controller/metal/rendering.rb:30:in `process_action' actionpack (5.1.4) lib/abstract_controller/callbacks.rb:20:in `block in process_action' activesupport (5.1.4) lib/active_support/callbacks.rb:131:in `run_callbacks' actionpack (5.1.4) lib/abstract_controller/callbacks.rb:19:in `process_action' actionpack (5.1.4) lib/action_controller/metal/rescue.rb:20:in `process_action' actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action' activesupport (5.1.4) lib/active_support/notifications.rb:166:in `block in instrument' activesupport (5.1.4) lib/active_support/notifications/instrumenter.rb:21:in `instrument' activesupport (5.1.4) lib/active_support/notifications.rb:166:in `instrument' actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:30:in `process_action' actionpack (5.1.4) lib/action_controller/metal/params_wrapper.rb:252:in `process_action' actionpack (5.1.4) lib/abstract_controller/base.rb:124:in `process' actionview (5.1.4) lib/action_view/rendering.rb:30:in `process' actionpack (5.1.4) lib/action_controller/metal.rb:189:in `dispatch' actionpack (5.1.4) lib/action_controller/metal.rb:253:in `dispatch' actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:49:in `dispatch' actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:31:in `serve' actionpack (5.1.4) lib/action_dispatch/journey/router.rb:50:in `block in serve' actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `each' actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `serve' actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:834:in `call' railties (5.1.4) lib/rails/engine.rb:522:in `call' railties (5.1.4) lib/rails/railtie.rb:185:in `public_send' railties (5.1.4) lib/rails/railtie.rb:185:in `method_missing' actionpack (5.1.4) lib/action_dispatch/routing/mapper.rb:17:in `block in ' actionpack (5.1.4) lib/action_dispatch/routing/mapper.rb:46:in `serve' actionpack (5.1.4) lib/action_dispatch/journey/router.rb:50:in `block in serve' actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `each' actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `serve' actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:834:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' rack-pjax (1.0.0) lib/rack/pjax.rb:12:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' omniauth (1.7.1) lib/omniauth/strategy.rb:190:in `call!' omniauth (1.7.1) lib/omniauth/strategy.rb:168:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' scout_apm (2.1.32) lib/scout_apm/instant/middleware.rb:53:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' scout_apm (2.1.32) lib/scout_apm/middleware.rb:15:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' rack (2.0.3) lib/rack/deflater.rb:34:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' remotipart (1.3.1) lib/remotipart/middleware.rb:32:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' warden (1.2.7) lib/warden/manager.rb:36:in `block in call' warden (1.2.7) lib/warden/manager.rb:35:in `catch' warden (1.2.7) lib/warden/manager.rb:35:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' rack (2.0.3) lib/rack/etag.rb:25:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' rack (2.0.3) lib/rack/conditional_get.rb:38:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' rack (2.0.3) lib/rack/head.rb:12:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context' rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' actionpack (5.1.4) lib/action_dispatch/middleware/cookies.rb:613:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' actionpack (5.1.4) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call' activesupport (5.1.4) lib/active_support/callbacks.rb:97:in `run_callbacks' actionpack (5.1.4) lib/action_dispatch/middleware/callbacks.rb:24:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' airbrake (7.1.0) lib/airbrake/rack/middleware.rb:52:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' actionpack (5.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' actionpack (5.1.4) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' chewy (0.10.1) lib/chewy/railtie.rb:19:in `block in call' chewy (0.10.1) lib/chewy/strategy.rb:70:in `wrap' chewy (0.10.1) lib/chewy.rb:200:in `strategy' chewy (0.10.1) lib/chewy/railtie.rb:19:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' railties (5.1.4) lib/rails/rack/logger.rb:36:in `call_app' railties (5.1.4) lib/rails/rack/logger.rb:24:in `block in call' activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `block in tagged' activesupport (5.1.4) lib/active_support/tagged_logging.rb:26:in `tagged' activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `tagged' railties (5.1.4) lib/rails/rack/logger.rb:24:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' actionpack (5.1.4) lib/action_dispatch/middleware/remote_ip.rb:79:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' actionpack (5.1.4) lib/action_dispatch/middleware/request_id.rb:25:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' rack (2.0.3) lib/rack/method_override.rb:22:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' rack (2.0.3) lib/rack/runtime.rb:22:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' activesupport (5.1.4) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' actionpack (5.1.4) lib/action_dispatch/middleware/static.rb:125:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' rack (2.0.3) lib/rack/sendfile.rb:111:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' hirefire-resource (0.4.2) lib/hirefire/middleware.rb:41:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' railties (5.1.4) lib/rails/engine.rb:522:in `call' newrelic_rpm (4.5.0.337) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call' puma (3.10.0) lib/puma/configuration.rb:225:in `call' puma (3.10.0) lib/puma/server.rb:605:in `handle_request' puma (3.10.0) lib/puma/server.rb:437:in `process_client' puma (3.10.0) lib/puma/server.rb:301:in `block in run' puma (3.10.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread' Request parameters {"utf8"=>"✓", "authenticity_token"=>"T7FHBgwLCCPJ+jjBZhWUqxua3yLHBxZ0SvoctGx0DgPNHcFvdzznvKmtTBpQtGhgayHppZecP1KxQ1BpHoj8lg==", "brand"=>{"name"=>"TestBrand", "pr_email"=>"", "press_enquiries"=>"", "market"=>"", "is_styles_user"=>"0", "countries"=>[""], "whitelisted_domains"=>"[]", "users"=>[""]}, "button"=>""} Session dump _csrf_token: "gqyGaXs3759gV3TbNqH8y3C7NodQmykm+7lM3XL88pU=" session_id: "d807af7e6e9ca572cde7ccea824aac18" warden.user.user.key: [["5a7ad6a59e6071323167ae22"], "$2a$10$0d3RZEy6Bi0utVMuYGvjme"] Env dump GATEWAY_INTERFACE: "CGI/1.2" HTTP_ACCEPT: "text/html, */*; q=0.01" HTTP_ACCEPT_ENCODING: "gzip, deflate, br" HTTP_ACCEPT_LANGUAGE: "fr,en;q=0.9" HTTP_ORIGIN: "http://localhost:3000" HTTP_VERSION: "HTTP/1.1" HTTP_X_CSRF_TOKEN: "T7FHBgwLCCPJ+jjBZhWUqxua3yLHBxZ0SvoctGx0DgPNHcFvdzznvKmtTBpQtGhgayHppZecP1KxQ1BpHoj8lg==" ORIGINAL_SCRIPT_NAME: "" REMOTE_ADDR: "::1" SERVER_NAME: "localhost" SERVER_PROTOCOL: "HTTP/1.1" Response headers None`

How can i resolve it on Trestle?

**Comment by kenzo2013** [comment]
Oups, 
I uncomment this
 params do |params|
    params.require(:brand).permit(:name)
  end
all work's well
